config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index new create show] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
  
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
   
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container d-flex justify-content-center">
  <h1>Restaurants</h1>
    <ul>
      <% @restaurants.each do |restaurant| %>
        <li><%= link_to restaurant.name, restaurant %></li>
      <% end %>
    </ul>

    <%= link_to "Add Restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :address %>
  </div>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1>Detalhe do Restaurante: <%= @restaurant.name %></h1>
  <p><b>Categoria:</b><%= @restaurant.category %></p>
  <a><b>Numero:</b><%= @restaurant.phone_number %></a>
  <p><b>Endereço: </b><%= @restaurant.address %></p>
  <p><b>Reviws: </b><%= @restaurant.review %></p>
  <%= link_to "Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
  <%= link_to 'Voltar para lista', restaurants_path %>
</div>

app/views/reviews/new.html.erb
<h1><strong>New review</strong></h1>

<div>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<p><strong>Reviews</strong></p>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>